### ISSUE TITLE
Site is down!

### ISSUE THREAD

**Issue by Carnaxus** [Rgghgh/Mute-Pack-Generator#2]
Just as the title says, your site (mc.rgghgh.com) is apparently completely offline, and this tool doesn't appear to have been rehosted anywhere else.  Please, these villagers are driving me _nutso_, help!

**Comment by Rgghgh** [comment]
Hello,
The site has been taken down due to web hosting costs, 
there is nothing I can really do about it right now.

My best offer is you set up the website locally? If you need any help with this,
 I will gladly answer any questions.

**Comment by Carnaxus** [comment]
How much was it costing you?

**Comment by Rgghgh** [comment]
Its not that expensive, [DigitalOcean](https://digitalocean.com) offers amazing rates.
The website wasn't really seeing much traffic and usage so I took it down.
